# Generated by Django 3.0.3 on 2020-03-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='gender',
        ),
    ]
