# Generated by Django 3.0.3 on 2020-03-09 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0002_remove_employee_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
