# Generated by Django 3.0.3 on 2020-03-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0003_employee_details_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='dob',
        ),
    ]
